const express = require('express')
const app = express()
const bodyParser = require('body-parser')
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))
app.listen(5000)
console.log('server started')
const StudentRouter = require('./router')
app.use('/fifth',StudentRouter.get())
